version: "2"
checks:
  argument-count:
    enabled: true
  complexity:
    enabled: true
  duplication:
    enabled: true
  file-lines:
    enabled: true
  method-lines:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  npath-complexity:
    enabled: true
  identical-code:
    enabled: true

plugins:
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 50
          paths:
            - "lib/**/*.rb"
  fixme:
    enabled: true

exclude_patterns:
  - "spec/"
  - "test/"
  - "vendor/"
  - "bin/"
  - "log/"
  - "tmp/"
  - "coverage/"