inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/IndentationWidth:
  Width: 2

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*'